// Role-Based Access Control (RBAC) Definitions & Permissions Matrix

export const ROLES = {
  STUDENT: "STUDENT",
  COUNSELLOR: "COUNSELLOR",
  VERIFICATION_OFFICER: "VERIFICATION_OFFICER",
  SUPER_ADMIN: "SUPER_ADMIN"
};

export const PERMISSIONS = {
  // Student Permissions
  VIEW_MARKETPLACE: [ROLES.STUDENT, ROLES.COUNSELLOR, ROLES.VERIFICATION_OFFICER, ROLES.SUPER_ADMIN],
  COMPARE_COUNSELLORS: [ROLES.STUDENT, ROLES.COUNSELLOR, ROLES.VERIFICATION_OFFICER, ROLES.SUPER_ADMIN],
  BOOK_ESCROW_SESSION: [ROLES.STUDENT, ROLES.SUPER_ADMIN],
  SUBMIT_INTAKE: [ROLES.STUDENT, ROLES.SUPER_ADMIN],
  SUBMIT_REVIEW: [ROLES.STUDENT, ROLES.SUPER_ADMIN],

  // Counsellor Permissions
  MANAGE_COUNSELLOR_PROFILE: [ROLES.COUNSELLOR, ROLES.SUPER_ADMIN],
  MANAGE_ROADMAP: [ROLES.COUNSELLOR, ROLES.SUPER_ADMIN],
  MANAGE_PIPELINE: [ROLES.COUNSELLOR, ROLES.SUPER_ADMIN],
  UPLOAD_PROOF: [ROLES.COUNSELLOR, ROLES.SUPER_ADMIN],
  RIGHT_OF_REPLY: [ROLES.COUNSELLOR, ROLES.SUPER_ADMIN],
  PURCHASE_BOOST: [ROLES.COUNSELLOR, ROLES.SUPER_ADMIN],

  // Admin Permissions
  VERIFY_COUNSELLORS: [ROLES.VERIFICATION_OFFICER, ROLES.SUPER_ADMIN],
  AUDIT_OFFER_LETTERS: [ROLES.VERIFICATION_OFFICER, ROLES.SUPER_ADMIN],
  MANAGE_BOOST_STATUS: [ROLES.SUPER_ADMIN],
  MANAGE_USER_ROLES: [ROLES.SUPER_ADMIN],
  VIEW_MONETIZATION_LEDGER: [ROLES.SUPER_ADMIN]
};

export const hasPermission = (userRole, permissionKey) => {
  const allowedRoles = PERMISSIONS[permissionKey] || [];
  return allowedRoles.includes(userRole);
};
